### ISSUE TITLE
Add link to docs in menubar

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch.github.io#4]
Should probably rename "Module Status" to something shorter while I'm at it.

Some reordering would also be in order.

**Comment by johan-bjareholt** [comment]
You improved the menubar a lot but forgot this!

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ActivityWatch/activitywatch.github.io/commit/269321a50ded1506b16a0b4ef07bcd7ec4077190
