### ISSUE TITLE
Track outbound links with Google Analytics

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch.github.io#8]
This is critical to be able to track conversions

**Comment by ErikBjare** [comment]
I think I fixed this today. Should look at the stats in a few days and then close.

**Comment by ErikBjare** [comment]
It's working! Closing.

**Comment by abhineet97** [comment]
Hi!
Did you implement this in e053e74?
Its causing all the links to open as popups (and then get blocked by the browser).

[Reverting](https://github.com/ActivityWatch/activitywatch.github.io/blob/84aff99a2f0529ecf72dd01701ce156709b435a1/_includes/analytics.pug#L40) back to setting `document.title` instead of calling `window.open()` should fix this.

Let me know if you need a PR!
My browser: Firefox 68.2.0esr (64-bit)

**Comment by ErikBjare** [comment]
@abhineet97 I believe that using `document.location = url` will break analytics (from what I remember), and we do want all outbound links to open in new tabs. But if you could test that out that would be great.

**Comment by abhineet97** [comment]
The [example](https://support.google.com/analytics/answer/7478520?hl=en) provided by Google also uses this approach.

Also, in the code, `document.location` is being set in a callback function. So, doesn't this mean that the document navigates _after_ the successful transmission of necessary analytics data?

Can you please share why you want outbound links to open in new tabs?
AFAIK, there's no straightforward way of opening a new tab through JavaScript.

Try checking the **Permissions** section of the **Privacy & Security** tab in your Firefox preferences.

**Comment by ErikBjare** [comment]
>Try checking the Permissions section of the Privacy & Security tab in your Firefox preferences.

Ah, found the exception.

>Also, in the code, document.location is being set in a callback function. So, doesn't this mean that the document navigates after the successful transmission of necessary analytics data?

Idk, I don't really remember the issue I had with `document.location` but maybe you're right. I'd appreciate it if you could submit a PR :slightly_smiling_face:
