### ISSUE TITLE
Navbar logo styling issue on chrome

### ISSUE THREAD

**Issue by je-l** [ActivityWatch/activitywatch.github.io#9]
The navbar logo looks too stretched on Chrome. Seems like a CSS issue.

![screencapture-activitywatch-net-2020-01-02-08_13_50](https://user-images.githubusercontent.com/17461971/71654053-380cc180-2d38-11ea-9aec-b48a3a3f2aeb.png)

**Comment by ErikBjare** [comment]
Well that's embarrassing, I'll look into it later today.

**Comment by ErikBjare** [comment]
Fixed, thanks for reporting!
